//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class MonsterTable_Client : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private string _Name;
		public string Name { get { return _Name; } set{_Name=value; } }

		[SerializeField]
		private long _Hp;
		public long Hp { get { return _Hp; } set{_Hp=value; } }

		[SerializeField]
		private int _DicePivot;
		public int DicePivot { get { return _DicePivot; } set{_DicePivot=value; } }

		[SerializeField]
		private int _RedDice;
		public int RedDice { get { return _RedDice; } set{_RedDice=value; } }

		[SerializeField]
		private long _GreenDice;
		public long GreenDice { get { return _GreenDice; } set{_GreenDice=value; } }

		[SerializeField]
		private long _PurpleDice;
		public long PurpleDice { get { return _PurpleDice; } set{_PurpleDice=value; } }

		[SerializeField]
		private string _Prefab;
		public string Prefab { get { return _Prefab; } set{_Prefab=value; } }


		public MonsterTable_Client()
		{
		}

#if UNITY_EDITOR
		public MonsterTable_Client(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _Name);
			TryParse(sheet[row][column++], out _Hp);
			TryParse(sheet[row][column++], out _DicePivot);
			TryParse(sheet[row][column++], out _RedDice);
			TryParse(sheet[row][column++], out _GreenDice);
			TryParse(sheet[row][column++], out _PurpleDice);
			TryParse(sheet[row][column++], out _Prefab);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class MonsterTable_MonsterTable_Client : EERowDataCollection
	{
		
		public List<MonsterTable_Client> elements = new List<MonsterTable_Client>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as MonsterTable_Client);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

	
public List<MonsterTable_Client> OnGetAllData()
		{		
return elements;
		}		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
