//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class PlayerTable_Client : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private string _Name;
		public string Name { get { return _Name; } set{_Name=value; } }

		[SerializeField]
		private int _Type;
		public int Type { get { return _Type; } set{_Type=value; } }

		[SerializeField]
		private long _Hp;
		public long Hp { get { return _Hp; } set{_Hp=value; } }

		[SerializeField]
		private int _TP;
		public int TP { get { return _TP; } set{_TP=value; } }

		[SerializeField]
		private long _Skill1;
		public long Skill1 { get { return _Skill1; } set{_Skill1=value; } }

		[SerializeField]
		private long _Skill2;
		public long Skill2 { get { return _Skill2; } set{_Skill2=value; } }

		[SerializeField]
		private long _Skill3;
		public long Skill3 { get { return _Skill3; } set{_Skill3=value; } }

		[SerializeField]
		private string _Prefab;
		public string Prefab { get { return _Prefab; } set{_Prefab=value; } }


		public PlayerTable_Client()
		{
		}

#if UNITY_EDITOR
		public PlayerTable_Client(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _Name);
			TryParse(sheet[row][column++], out _Type);
			TryParse(sheet[row][column++], out _Hp);
			TryParse(sheet[row][column++], out _TP);
			TryParse(sheet[row][column++], out _Skill1);
			TryParse(sheet[row][column++], out _Skill2);
			TryParse(sheet[row][column++], out _Skill3);
			TryParse(sheet[row][column++], out _Prefab);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class PlayerTable_PlayerTable_Client : EERowDataCollection
	{
		
		public List<PlayerTable_Client> elements = new List<PlayerTable_Client>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as PlayerTable_Client);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

	
public List<PlayerTable_Client> OnGetAllData()
		{		
return elements;
		}		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
