//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class StageTable_Client : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private string _Name;
		public string Name { get { return _Name; } set{_Name=value; } }

		[SerializeField]
		private string _Reward;
		public string Reward { get { return _Reward; } set{_Reward=value; } }

		[SerializeField]
		private string _Description;
		public string Description { get { return _Description; } set{_Description=value; } }


		public StageTable_Client()
		{
		}

#if UNITY_EDITOR
		public StageTable_Client(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _Name);
			TryParse(sheet[row][column++], out _Reward);
			TryParse(sheet[row][column++], out _Description);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class StageTable_StageTable_Client : EERowDataCollection
	{
		
		public List<StageTable_Client> elements = new List<StageTable_Client>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as StageTable_Client);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

	
public List<StageTable_Client> OnGetAllData()
		{		
return elements;
		}		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
