//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace SheetData
{
	[Serializable]
	public class StageGroupTable_Client : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private long _UID;
		public long UID { get { return _UID; } set{_UID=value; } }

		[SerializeField]
		private long _Main_UID;
		public long Main_UID { get { return _Main_UID; } set{_Main_UID=value; } }

		[SerializeField]
		private int _Main_SlotIndex;
		public int Main_SlotIndex { get { return _Main_SlotIndex; } set{_Main_SlotIndex=value; } }

		[SerializeField]
		private long _Battle1_UID;
		public long Battle1_UID { get { return _Battle1_UID; } set{_Battle1_UID=value; } }

		[SerializeField]
		private int _Battle1_SlotIndex;
		public int Battle1_SlotIndex { get { return _Battle1_SlotIndex; } set{_Battle1_SlotIndex=value; } }

		[SerializeField]
		private long _Battle2_UID;
		public long Battle2_UID { get { return _Battle2_UID; } set{_Battle2_UID=value; } }

		[SerializeField]
		private int _Battle2_SlotIndex;
		public int Battle2_SlotIndex { get { return _Battle2_SlotIndex; } set{_Battle2_SlotIndex=value; } }

		[SerializeField]
		private long _Event1_UID;
		public long Event1_UID { get { return _Event1_UID; } set{_Event1_UID=value; } }

		[SerializeField]
		private int _Event1_SlotIndex;
		public int Event1_SlotIndex { get { return _Event1_SlotIndex; } set{_Event1_SlotIndex=value; } }

		[SerializeField]
		private long _Event2_UID;
		public long Event2_UID { get { return _Event2_UID; } set{_Event2_UID=value; } }

		[SerializeField]
		private int _Event2_SlotIndex;
		public int Event2_SlotIndex { get { return _Event2_SlotIndex; } set{_Event2_SlotIndex=value; } }


		public StageGroupTable_Client()
		{
		}

#if UNITY_EDITOR
		public StageGroupTable_Client(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _UID);
			TryParse(sheet[row][column++], out _Main_UID);
			TryParse(sheet[row][column++], out _Main_SlotIndex);
			TryParse(sheet[row][column++], out _Battle1_UID);
			TryParse(sheet[row][column++], out _Battle1_SlotIndex);
			TryParse(sheet[row][column++], out _Battle2_UID);
			TryParse(sheet[row][column++], out _Battle2_SlotIndex);
			TryParse(sheet[row][column++], out _Event1_UID);
			TryParse(sheet[row][column++], out _Event1_SlotIndex);
			TryParse(sheet[row][column++], out _Event2_UID);
			TryParse(sheet[row][column++], out _Event2_SlotIndex);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class StageGroupTable_StageGroupTable_Client : EERowDataCollection
	{
		
		public List<StageGroupTable_Client> elements = new List<StageGroupTable_Client>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as StageGroupTable_Client);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

	
public List<StageGroupTable_Client> OnGetAllData()
		{		
return elements;
		}		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
